### PR TITLE
Add support for Django 1.11 & 2.x

### PR DESCRIPTION
**Pull request by jleclanche**
This PR drops support for now-unsupported versions of Django, leaves only Django 1.11, and adds compatibility with Django 2.0, 2.1 and 2.2.

### CODE REVIEW

**Comment by jleclanche** [comment]
Ok tests are green :)

**Comment by willseward** [comment]
@jleclanche Thanks for the support!

**Comment by jleclanche** [comment]
@willseward thank you! Let me know if you need help for a pypi release :)

**Comment by jleclanche** [comment]
@willseward sorry to bug you again ;) but any chance for a release on pypi?

**Comment by willseward** [comment]
@jleclanche thanks for the nudge! Enjoy: https://pypi.org/manage/project/django-custom-field/release/3.0/

**Comment by jleclanche** [comment]
Thanks!

**Comment by jleclanche** [comment]
PS, if you get tired of maintaining this, Jazzband is a good option :) https://github.com/jazzband https://jazzband.co/

**Pull request merged**
